version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - npm install

  build:
    commands:                                                               #this is for nodejs
      - npm install -g pkg
      - npm run build

  post_build:
    commands:
      # Install Snyk
      - npm install -g snyk

      # Authenticate Snyk with your Snyk account
      - snyk auth $SNYK_TOKEN

      # Run Snyk test to check for vulnerabilities
      - snyk test

      # If you want to fail the build on vulnerabilities above a certain severity, use the following command
      # - snyk test --severity-threshold=high

      # Sync the build artifacts to S3 bucket
      - aws s3 sync dist/ s3://${BUCKET_NAME}/

      # Copy index.html to S3
      - aws s3 cp index.html s3://${BUCKET_NAME}/

artifacts:
  files: '**/*'
  base-directory: dist
  discard-paths: yes
